pipeline {
	agent { label "docker" }
	environment {
                DH_UN="akashcm"
	}
	stages {
		stage ('Checkout') {
			steps {
				git branch: 'main', url: 'https://github.com/Akashcm731/java-example_war.git'
			}
		}
		stage ('Build Stage') {
			steps {
				sh 'docker build -t ${DH_UN}/assi:${BUILD_NUMBER} .'
			}
		}
		stage ('Push Stage') {
			steps {
				sh 'docker push ${DH_UN}/assi:${BUILD_NUMBER}'
			}
		}
		stage ('Deploy Stage') {
			steps {
				sh 'docker run -d --name cont_${BUILD_NUMBER} -p 8080:8080 ${DH_UN}/assi:${BUILD_NUMBER}'
			}
		}
	}	
}
